"""new migration

Revision ID: 3734ab5d07c1
Revises: 8fdda8e694d9
Create Date: 2024-02-25 08:49:21.809392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3734ab5d07c1'
down_revision = '8fdda8e694d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enclosure')
    op.drop_table('feeding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeding',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enclosure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('food', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name='feeding_animal_id_fkey'),
    sa.ForeignKeyConstraint(['enclosure_id'], ['enclosure.id'], name='feeding_enclosure_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='feeding_pkey')
    )
    op.create_table('enclosure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='enclosure_pkey')
    )
    # ### end Alembic commands ###
